apiVersion: v1
kind: Service
metadata:
  name: backend
  # namespace: blue
spec:
  type: LoadBalancer
  selector:
    app: bubble
    tier: backend
    color: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  
