apiVersion: v1
kind: Service
metadata:
  name: frontend
  # namespace: blue
spec:
  type: LoadBalancer
  selector:
    app: bubble
    tier: frontend
    color: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

